### ISSUE TITLE
Issue using save_doc/3 with Map (or ICouch.Document)

### ISSUE THREAD

**Issue by kiere** [meetnow/icouch#1]
```Elixir
** (FunctionClauseError) no function clause matching in ICouch.DB.server_endpoint/2

    The following arguments were given to ICouch.DB.server_endpoint/2:

        # 1
        %ICouch.DB{name: "my-test-db",
     server: %ICouch.Server{direct: nil,
      ib_options: [basic_auth: {'username', 'password'}], timeout: nil,
      uri: %URI{authority: "127.0.0.1:5984", fragment: nil, host: "127.0.0.1",
       path: "/", port: 5984, query: nil, scheme: "http", userinfo: nil}}}

        # 2
        {nil, []}

    Attempted function clauses (showing 3 out of 3):

        def server_endpoint(%ICouch.DB{name: db_name}, {path, options}) when is_binary(path)
        def server_endpoint(%ICouch.DB{name: db_name}, %URI{path: path} = endpoint)
        def server_endpoint(%ICouch.DB{name: db_name}, endpoint) when is_binary(endpoint)

    (icouch) lib/icouch/db.ex:65: ICouch.DB.server_endpoint/2
    (icouch) lib/icouch/db.ex:33: ICouch.DB.send_req/4
    (icouch) lib/icouch.ex:526: ICouch.save_doc/3
```

### Steps to Reproduce

```Elixir
# Create server connection
server = ICouch.server_connection("http://127.0.0.1:5984/", basic_auth: {"username", "password"})

# Open database
{:ok, db} = ICouch.open_db(server, "my-test-db")

# Try to insert a document
doc = ICouch.save_doc(db, %{name: "Someone", email: "somebody@example.org"})
# Boom!

# Second approach
doc = ICouch.Document.new(%{name: "Someone", email: "somebody@example.org"})
new_doc = ICouch.save_doc(db, doc)
# Same Boom!
```

I'd appreciate any advise if I'm reading the docs incorrectly.

**Comment by p2k** [comment]
Thanks for your report. The implementation in does in fact not follow the documentation and there is no test case for this yet.

What you are doing "wrong" is trying to insert a document without id. However, `ICouch.save_doc` should - as documented - obtain a new id automatically, which means this is an error of ICouch.

A fix will follow shortly.

PS: You could also put username and password into the URL (depends on how you configure your project):
```
server = ICouch.server_connection("http://username:password@127.0.0.1:5984/")
```

PPS: Using `ICouch.save_doc` with a Map will implicitly convert it to an `ICouch.Document` so the behavior will not be different.
